### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by mattiaburati** [insideGen/Loupedeck-AudioControl-OpenPlugin#5]
the plugin is not working anymore. I think because of the new loupedeck update

**Comment by RadiatorTwo** [comment]
Check out my fork.
Converted it to the new SDK 6 and created a release.
Did also create a pull request yesterday, but I don´t know if @insideGen is still active.

**Comment by insideGen** [comment]
New version 2.0.0-beta.1 is pre-released: [https://github.com/insideGen/Loupedeck-AudioControl-OpenPlugin/releases/tag/v2.0.0-beta.1]()
Thanks @RadiatorTwo for your pull request 😉
